allowBuilds:
    esbuild: false
    sharp: true
    workerd: true
catalog:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plus: latest
minimumReleaseAgeExclude:
    - "@voidzero-dev/*"
    - vite-plus
overrides:
    vite: "catalog:"
peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: "*"
