shellEmulator: true
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  "@prisma/engines": false
  esbuild: false
  prisma: false
  sharp: true
  workerd: true
